### ISSUE TITLE
 youtube-downloader broken by PySide2 and shiboken2 upgrade to 5.15.2

### ISSUE THREAD

**Issue by Armag67** [blooser/youtube-downloader#2]
Hello,
Last upgrade of PySide2 and shiboken2 to 5.15.2 version breaks youtube-downloader with this traceback:
```
Traceback (most recent call last):
  File "/home/h2/.local/bin/youtube-downloader", line 5, in <module>
    from youtubedownloader import main
  File "/home/h2/.local/lib/python3.8/site-packages/youtubedownloader/__init__.py", line 7, in <module>
    from .download import DownloadManager, FileDownloader
  File "/home/h2/.local/lib/python3.8/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "/home/h2/.local/lib/python3.8/site-packages/youtubedownloader/download.py", line 310, in <module>
    class DownloadData(QObject):
  File "/home/h2/.local/lib/python3.8/site-packages/youtubedownloader/download.py", line 325, in DownloadData
    def title(self) -> str:
TypeError: A constant property cannot have a WRITE method or a NOTIFY signal.
```
While `pip check` and `pipdeptree` don't show any dependency mismatch for youtube-downloader.

Thanks for taking a look and have a nice day.

**Comment by blooser** [comment]
Hello @Armag67 

Thank you for the issue!

I analyzed it and it looks like an issue in PySide2. Youtube Downloader works fine for the 5.15.0 version. I introduced the d8a0b7d to fix it.

I also created a new issue on the PySide2 bug trace (https://bugreports.qt.io/browse/PYSIDE-1426), suppose they will fix it.
